version: "3.9"

services:
  datastores:
    image: postgres:15
    container_name: music_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: music_backend
    env_file:
      - ./backend/.env
    environment:
      PG_URL: postgresql+asyncpg://postgres:postgres@datastores:5432/music
    depends_on:
      datastores:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  # frontend:
  #   build: ./frontend
  #   container_name: music_frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  pgdata:
